# Generated by Django 4.0.6 on 2023-05-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('locker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('occupied', models.BooleanField(default=False)),
                ('broken', models.BooleanField(default=False)),
            ],
        ),
    ]
