# Generated by Django 4.2.1 on 2023-06-04 20:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locker", "0002_application"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Application",
            new_name="Appointment",
        ),
    ]
